# Site settings
title: Tom Mault
tag_text: Tom Mault
description: Graduate Consultant at Atos. Currently studying the Intro to Programming Nanodegree on Udacity. I graduated from Loughborough University in Summer 2015 with a degree in Geography and Management.

# Build settings
markdown: kramdown

exclude: ["README.md"]
